application: api-cotefe-net
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# CRON

# - url: /report/weekly
#   script: reports.py
#   login: admin
  
# WEB INTERFACE

- url: /css
  static_dir: static/css
  
- url: /pics
  static_dir: static/pics
  
- url: /scripts
  static_dir: static/scripts
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on

inbound_services:
- warmup