application: api-cotefe-net
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: static/css
  
- url: /pics
  static_dir: static/pics
  
- url: /scripts
  static_dir: static/scripts
  
- url: /favicon\.ico
  static_files: static/pics/favicon.ico
  upload: static/pics/favicon\.ico

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on

inbound_services:
- warmup