application: api-cotefe-net
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: static/css
  
- url: /images
  static_dir: static/images
  
- url: /scripts
  static_dir: static/scripts
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: main.app
  secure: optional

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest