MEDIA_TYPE = 'application/json'

JSON_INDENT = 4
JSON_ENSURE_ASCII = True

# TESTBED ADAPTATION/ABSTRACTION API (TAA)
TAA_PROTOCOL = 'http'
TAA_HOST = 'localhost'
TAA_PORT = '8001'

# TESTBED NATIVE API (TNA)
XMLRPC_PROTOCOL = 'https'
XMLRPC_HOST = '127.0.0.1'
XMLRPC_PORT = '8005'
XMLRPC_USERNAME = 'conetuser'
XMLRPC_PASSWORD = 'password'