from django.contrib import admin
from django.contrib import databrowse
from api.models import *

#admin.site.register(UserProfile)
admin.site.register(Testbed)
admin.site.register(Job)
admin.site.register(Task)
admin.site.register(Trace)
admin.site.register(Log)
admin.site.register(ImageFormat)
admin.site.register(Image)
admin.site.register(Platform)
admin.site.register(Interface)
admin.site.register(Radio)
admin.site.register(Sensor)
admin.site.register(Actuator)
admin.site.register(Mobility)
admin.site.register(Node)
admin.site.register(NodeGroup)
admin.site.register(Socket)

#databrowse.site.register(UserProfile)
databrowse.site.register(Testbed)
databrowse.site.register(Job)
databrowse.site.register(Task)
databrowse.site.register(Trace)
databrowse.site.register(Log)
databrowse.site.register(ImageFormat)
databrowse.site.register(Image)
databrowse.site.register(Platform)
databrowse.site.register(Interface)
databrowse.site.register(Radio)
databrowse.site.register(Sensor)
databrowse.site.register(Actuator)
databrowse.site.register(Mobility)
databrowse.site.register(Node)
databrowse.site.register(NodeGroup)
databrowse.site.register(Socket)