MEDIA_TYPE = 'application/json'

JSON_INDENT = 4
JSON_ENSURE_ASCII = True

# TESTBED ADAPTATION API
SERVER_PROTOCOL = 'http'
SERVER_HOST = 'localhost'
SERVER_PORT = '8001'

XMLRPC_PROTOCOL = 'https'
XMLRPC_USERNAME = 'conetuser'
XMLRPC_PASSWORD = 'password'
XMLRPC_HOST = 'localhost'
XMLRPC_PORT = '8005'