application: conet-testbed-federation
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /index\.html
  script: home.py
  
- url: /
  static_dir: static
  
- url: /admin/.*
  script: admin.py
  login: admin
  
- url: /api/.*
  script: main.py
  secure: always
  
- url: /init
  script: init.py
  login: admin
  
- url: /.*
  script: not_found.py
